### WARNING: The full submission, including this file, will be made public. ###
# This is a TOML file https://toml.io/en/.

# Name of the submission.
# This name must change at every new submission you make.
name = "Demo-1"
# Team name, must be the same as the registered user name on the submission server.
team = "Organizers"
# Author list (pseudonyms allowed).
# Email is optional, but we need at least one corresponding author.
authors = [
        { name = "Gaëtan Cassiers", email = "gaetan.cassiers@iaik.tugraz.at", corresponding = true },
        { name = "Charles Momin", email = "charles.momin@uclouvain.be", corresponding = true },
]
# License for all the code in this submission (unless noted otherwise in
# individual files or in a LICENSE, COPYRIGHT or COPYING.
# If applicable, give the SPDX ID of the license (https://spdx.org/licenses/),
# otherwise the full license text an unambiguous reference to the license.
# In any case, the license must be an open-source license (https://opensource.org/osd/).
# We recomment using the Apache-2.0 license or the  GPL-3.0-or-later license.
license = "Apache-2.0"

# Choose which target your attack applies to.
[attacks.A7_d2]
# Number of attack traces (this does not impact the availability of the full profiling dataset).
n_traces = 16777215
